int led1=13;//red
int led2=9;//yellow
int led3=5;//green
void setup() {
  // put your setup code here, to run once:
  pinMode(led1,OUTPUT);
  pinMode(led2,OUTPUT);
  pinMode(led3,OUTPUT);

}

void loop() {
  // put your main code here, to run repeatedly:
  //led1
  digitalWrite(led1,HIGH);
  delay(100);
  digitalWrite(led1,LOW);
  delay(100);
  digitalWrite(led1,HIGH);
  delay(100);
  digitalWrite(led1,LOW);
  delay(100);
  digitalWrite(led1,HIGH);
  delay(100);
  digitalWrite(led1,LOW);
  delay(100);
  digitalWrite(led1,HIGH);
  delay(100);
  digitalWrite(led1,LOW);
  delay(100);
  digitalWrite(led1,HIGH);
  delay(100);
  digitalWrite(led1,LOW);
  delay(100);
  //led2
  digitalWrite(led2,HIGH);
  delay(100);
  digitalWrite(led2,LOW);
  delay(100);
  digitalWrite(led2,HIGH);
  delay(100);
  digitalWrite(led2,LOW);
  delay(100);
  digitalWrite(led2,HIGH);
  delay(100);
  digitalWrite(led2,LOW);
  delay(100);
  digitalWrite(led2,HIGH);
  delay(100);
  digitalWrite(led2,LOW);
  delay(100);
  digitalWrite(led2,HIGH);
  delay(100);
  digitalWrite(led2,LOW);
  delay(100);
   digitalWrite(led2,HIGH);
  delay(100);
  digitalWrite(led2,LOW);
  delay(100);
  digitalWrite(led2,HIGH);
  delay(100);
  digitalWrite(led2,LOW);
  delay(100);
  digitalWrite(led2,HIGH);
  delay(100);
  digitalWrite(led2,LOW);
  delay(100);
  digitalWrite(led2,HIGH);
  delay(100);
  digitalWrite(led2,LOW);
  delay(100);
  digitalWrite(led2,HIGH);
  delay(100);
  digitalWrite(led2,LOW);
  delay(100);
  //led3
  digitalWrite(led3,HIGH);
  delay(100);
  digitalWrite(led3,LOW);
  delay(100);
  digitalWrite(led3,HIGH);
  delay(100);
  digitalWrite(led3,LOW);
  delay(100);
  digitalWrite(led3,HIGH);
  delay(100);
  digitalWrite(led3,LOW);
  delay(100);
  digitalWrite(led3,HIGH);
  delay(100);
  digitalWrite(led3,LOW);
  delay(100);
  digitalWrite(led3,HIGH);
  delay(100);
  digitalWrite(led3,LOW);
  delay(100);
  digitalWrite(led3,HIGH);
  delay(100);
  digitalWrite(led3,LOW);
  delay(100);
  digitalWrite(led3,HIGH);
  delay(100);
  digitalWrite(led3,LOW);
  delay(100);
  digitalWrite(led3,HIGH);
  delay(100);
  digitalWrite(led3,LOW);
  delay(100);
  digitalWrite(led3,HIGH);
  delay(100);
  digitalWrite(led3,LOW);
  delay(100);
  digitalWrite(led3,HIGH);
  delay(100);
  digitalWrite(led3,LOW);
  delay(100);
   digitalWrite(led3,HIGH);
  delay(100);
  digitalWrite(led3,LOW);
  delay(100);
  digitalWrite(led3,HIGH);
  delay(100);
  digitalWrite(led3,LOW);
  delay(100);
  digitalWrite(led3,HIGH);
  delay(100);
  digitalWrite(led3,LOW);
  delay(100);
  digitalWrite(led3,HIGH);
  delay(100);
  digitalWrite(led3,LOW);
  delay(100);
  digitalWrite(led3,HIGH);
  delay(100);
  digitalWrite(led3,LOW);
  delay(100);
  digitalWrite(led3,HIGH);
  delay(100);
  digitalWrite(led3,LOW);
  delay(100);
  digitalWrite(led3,HIGH);
  delay(100);
  digitalWrite(led3,LOW);
  delay(100);
  digitalWrite(led3,HIGH);
  delay(100);
  digitalWrite(led3,LOW);
  delay(100);
  digitalWrite(led3,HIGH);
  delay(100);
  digitalWrite(led3,LOW);
  delay(100);
  digitalWrite(led3,HIGH);
  delay(100);
  digitalWrite(led3,LOW);
  delay(100);

}
